name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.3
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: |
          --exclude '.git*'
          --exclude '.github*'
          --exclude 'node_modules'
        host: 54.176.126.106
        username: ubuntu
        port: 22
        source: '.'
        target: '/var/www/html/your_project'
